/**
 * Software Development Onboarding Template
 * Comprehensive onboarding flow for software/app development projects
 */

import { OnboardingStep } from '../ai-onboarding-analyzer';

export const softwareDevTemplate: OnboardingStep[] = [
  {
    type: 'welcome',
    title: 'Welcome to Your Software Development Project',
    description: `Thank you for choosing us for your software development project! This onboarding will take approximately 35-40 minutes and will help us gather all technical requirements, user needs, and project specifications. Your detailed responses will ensure we build exactly what you envision. Let's get started!`,
    required: true,
    estimatedMinutes: 2,
  },
  {
    type: 'form',
    title: 'Project Overview',
    description: 'Tell us about your software project at a high level',
    fields: [
      {
        name: 'projectName',
        label: 'Project Name',
        type: 'text',
        placeholder: 'e.g., Customer Portal, Mobile App, Internal Tool',
        required: true,
      },
      {
        name: 'projectType',
        label: 'Type of Software',
        type: 'select',
        options: [
          'Web Application',
          'Mobile App (iOS)',
          'Mobile App (Android)',
          'Mobile App (Cross-platform)',
          'Desktop Application',
          'API/Backend Service',
          'Chrome Extension/Browser Plugin',
          'Other',
        ],
        required: true,
      },
      {
        name: 'projectDescription',
        label: 'Project Description',
        type: 'textarea',
        placeholder: 'Describe what your software should do and the problems it will solve...',
        required: true,
        helpText: 'Be as detailed as possible about functionality and purpose',
      },
      {
        name: 'targetUsers',
        label: 'Who will use this software?',
        type: 'textarea',
        placeholder: 'e.g., Internal employees, External customers, B2B clients, General public',
        required: true,
      },
      {
        name: 'estimatedUsers',
        label: 'Expected number of users',
        type: 'select',
        options: [
          '1-10 users',
          '10-50 users',
          '50-500 users',
          '500-5,000 users',
          '5,000-50,000 users',
          '50,000+ users',
        ],
        required: false,
      },
    ],
    required: true,
    estimatedMinutes: 8,
  },
  {
    type: 'form',
    title: 'Core Features & Requirements',
    description: 'Define the main features and functionality',
    fields: [
      {
        name: 'coreFeatures',
        label: 'What are the core features? (List the top 5-10)',
        type: 'textarea',
        placeholder: 'e.g.,\n- User registration and login\n- Dashboard with analytics\n- Payment processing\n- File uploads',
        required: true,
        helpText: 'List each feature on a new line',
      },
      {
        name: 'userAuthentication',
        label: 'User Authentication Requirements',
        type: 'checkbox',
        options: [
          'Email/password login',
          'Social login (Google, Facebook, etc.)',
          'Two-factor authentication (2FA)',
          'Single sign-on (SSO)',
          'Guest/anonymous access',
          'No authentication needed',
        ],
        required: true,
      },
      {
        name: 'userRoles',
        label: 'User Roles & Permissions',
        type: 'textarea',
        placeholder: 'e.g.,\n- Admin: Full access\n- Manager: View and edit\n- User: View only',
        required: false,
        helpText: 'Describe different user types and their access levels',
      },
      {
        name: 'dataManagement',
        label: 'What kind of data will the app manage?',
        type: 'textarea',
        placeholder: 'e.g., Customer records, Inventory items, Financial transactions, Documents',
        required: true,
      },
      {
        name: 'fileUploads',
        label: 'Will users need to upload files?',
        type: 'radio',
        options: ['Yes', 'No', 'Maybe/Not sure'],
        required: true,
      },
    ],
    required: true,
    estimatedMinutes: 10,
  },
  {
    type: 'form',
    title: 'Technical Preferences',
    description: 'Share any technical requirements or preferences',
    fields: [
      {
        name: 'techStackPreference',
        label: 'Do you have technology stack preferences?',
        type: 'select',
        options: [
          'No preference - recommend best option',
          'Specific framework required (specify below)',
          'Match existing tech stack',
          'Modern/cutting-edge preferred',
          'Stable/proven technologies preferred',
        ],
        required: true,
      },
      {
        name: 'specificTechnologies',
        label: 'Specific technologies required (if any)',
        type: 'textarea',
        placeholder: 'e.g., React, Node.js, Python, AWS, etc.',
        required: false,
      },
      {
        name: 'database',
        label: 'Database requirements',
        type: 'select',
        options: [
          'No preference',
          'SQL (PostgreSQL, MySQL)',
          'NoSQL (MongoDB, DynamoDB)',
          'Must integrate with existing database',
        ],
        required: false,
      },
      {
        name: 'hostingPreference',
        label: 'Hosting & Infrastructure',
        type: 'select',
        options: [
          'Cloud hosting (AWS, Google Cloud, Azure)',
          'Specific provider required',
          'On-premise/self-hosted',
          'No preference',
        ],
        required: false,
      },
      {
        name: 'scalability',
        label: 'Scalability requirements',
        type: 'select',
        options: [
          'Start small, scale later',
          'Must handle high traffic from day 1',
          'Moderate growth expected',
          'Not sure',
        ],
        required: false,
      },
    ],
    required: false,
    estimatedMinutes: 7,
  },
  {
    type: 'form',
    title: 'Integrations & APIs',
    description: 'Identify any third-party integrations needed',
    fields: [
      {
        name: 'thirdPartyIntegrations',
        label: 'Third-party services to integrate',
        type: 'checkbox',
        options: [
          'Payment processing (Stripe, PayPal)',
          'Email service (SendGrid, Mailgun)',
          'SMS/notifications (Twilio)',
          'Analytics (Google Analytics, Mixpanel)',
          'Cloud storage (AWS S3, Dropbox)',
          'CRM (Salesforce, HubSpot)',
          'Accounting (QuickBooks, Xero)',
          'Calendar (Google Calendar, Outlook)',
          'Other (specify below)',
        ],
        required: false,
      },
      {
        name: 'otherIntegrations',
        label: 'Other integrations or APIs',
        type: 'textarea',
        placeholder: 'List any other services, APIs, or systems to integrate with...',
        required: false,
      },
      {
        name: 'existingSystems',
        label: 'Do you have existing systems to integrate with?',
        type: 'textarea',
        placeholder: 'Describe existing databases, software, or internal systems...',
        required: false,
      },
    ],
    required: false,
    estimatedMinutes: 6,
  },
  {
    type: 'choice',
    title: 'Design & UI Preferences',
    description: 'Select design styles that match your vision',
    choices: [
      {
        id: 'modern_clean',
        label: 'Modern & Clean',
        description: 'Minimalist interface, lots of white space, easy to navigate',
      },
      {
        id: 'data_rich',
        label: 'Data-Rich Dashboard',
        description: 'Charts, tables, analytics - information at a glance',
      },
      {
        id: 'material_design',
        label: 'Material Design',
        description: 'Google-style interface with cards and smooth animations',
      },
      {
        id: 'enterprise',
        label: 'Enterprise/Professional',
        description: 'Corporate aesthetic, functional and business-focused',
      },
      {
        id: 'colorful_engaging',
        label: 'Colorful & Engaging',
        description: 'Vibrant colors, playful elements, fun user experience',
      },
      {
        id: 'dark_mode',
        label: 'Dark Mode First',
        description: 'Dark theme as primary design, modern and sleek',
      },
    ],
    required: false,
    estimatedMinutes: 4,
  },
  {
    type: 'upload',
    title: 'Technical Documentation & Assets',
    description: 'Upload any relevant technical documents or design files',
    uploadCategories: [
      {
        name: 'wireframes',
        label: 'Wireframes/Mockups',
        description: 'UI designs, wireframes, or mockups you\'ve created',
        accept: 'image/*,.pdf,.fig,.sketch,.xd',
        maxFiles: 10,
        required: false,
      },
      {
        name: 'technical_docs',
        label: 'Technical Documentation',
        description: 'Requirements docs, API specs, database schemas',
        accept: '.pdf,.doc,.docx,.txt,.md',
        maxFiles: 10,
        required: false,
      },
      {
        name: 'existing_code',
        label: 'Existing Codebase (if any)',
        description: 'Zip file of existing code or link to repository',
        accept: '.zip,.tar,.gz',
        maxFiles: 3,
        required: false,
      },
      {
        name: 'design_assets',
        label: 'Design Assets',
        description: 'Logos, icons, brand guidelines, style guides',
        accept: 'image/*,.pdf,.svg,.ai',
        maxFiles: 10,
        required: false,
      },
    ],
    required: false,
    estimatedMinutes: 6,
  },
  {
    type: 'form',
    title: 'Security & Compliance',
    description: 'Important security and compliance considerations',
    fields: [
      {
        name: 'dataPrivacy',
        label: 'Data privacy requirements',
        type: 'checkbox',
        options: [
          'GDPR compliance (EU users)',
          'HIPAA compliance (healthcare data)',
          'PCI DSS compliance (payment data)',
          'SOC 2 compliance',
          'Other regulatory requirements',
        ],
        required: false,
      },
      {
        name: 'securityFeatures',
        label: 'Security features needed',
        type: 'checkbox',
        options: [
          'Data encryption at rest',
          'Data encryption in transit (SSL/TLS)',
          'Regular security audits',
          'Penetration testing',
          'User activity logging',
          'Backup and disaster recovery',
        ],
        required: false,
      },
      {
        name: 'complianceNotes',
        label: 'Additional security or compliance notes',
        type: 'textarea',
        placeholder: 'Any specific security requirements or compliance standards...',
        required: false,
      },
    ],
    required: false,
    estimatedMinutes: 5,
  },
  {
    type: 'form',
    title: 'Timeline & Budget',
    description: 'Project timeline and budget expectations',
    fields: [
      {
        name: 'targetLaunchDate',
        label: 'Target launch date',
        type: 'date',
        required: false,
        helpText: 'When would you ideally like to launch?',
      },
      {
        name: 'timeline',
        label: 'Timeline flexibility',
        type: 'select',
        options: [
          'Fixed deadline - must launch by target date',
          'Flexible - quality over speed',
          'ASAP - as fast as possible',
        ],
        required: false,
      },
      {
        name: 'projectPhases',
        label: 'Would you prefer phased development?',
        type: 'radio',
        options: [
          'Yes - MVP first, then additional features',
          'No - build everything at once',
          'Open to recommendation',
        ],
        required: false,
      },
      {
        name: 'budgetRange',
        label: 'Budget range (optional)',
        type: 'select',
        options: [
          'Under $10,000',
          '$10,000 - $25,000',
          '$25,000 - $50,000',
          '$50,000 - $100,000',
          'Over $100,000',
          'Prefer not to disclose',
        ],
        required: false,
      },
      {
        name: 'additionalNotes',
        label: 'Any other important details?',
        type: 'textarea',
        placeholder: 'Anything else we should know about your project, timeline, or requirements...',
        required: false,
      },
    ],
    required: false,
    estimatedMinutes: 6,
  },
  {
    type: 'review',
    title: 'Review Your Project Details',
    description: `Please carefully review all technical requirements, features, and project details. Make sure everything is accurate before submitting.`,
    required: true,
    estimatedMinutes: 4,
  },
  {
    type: 'complete',
    title: 'Project Onboarding Complete!',
    description: `Thank you for providing such detailed information! Our development team will review your requirements and prepare a comprehensive project plan, including architecture design, technology recommendations, and timeline estimate. You'll receive an email within 24-48 hours with next steps and a proposed development roadmap. We're excited to build your software!`,
    required: true,
    estimatedMinutes: 1,
  },
];
