/**
 * Voice AI Campaign Onboarding Template
 * Onboarding flow for AI voice calling campaigns
 */

import { OnboardingStep } from '../ai-onboarding-analyzer';

export const voiceAITemplate: OnboardingStep[] = [
  {
    type: 'welcome',
    title: 'Welcome to Your Voice AI Campaign',
    description: `Welcome! This onboarding will take approximately 30-35 minutes. We'll gather everything needed to create and launch your AI-powered calling campaign. You can save your progress at any time and return later. Let's build something amazing together!`,
    required: true,
    estimatedMinutes: 2,
  },
  {
    type: 'form',
    title: 'Campaign Overview',
    description: 'Tell us about your campaign goals and objectives',
    fields: [
      {
        name: 'campaignName',
        label: 'Campaign Name',
        type: 'text',
        placeholder: 'e.g., Q4 Lead Generation Campaign',
        required: true,
      },
      {
        name: 'campaignGoal',
        label: 'Primary Campaign Goal',
        type: 'select',
        options: [
          'Lead generation',
          'Appointment setting',
          'Customer surveys',
          'Event invitations',
          'Product announcements',
          'Follow-up calls',
          'Customer retention',
          'Other',
        ],
        required: true,
      },
      {
        name: 'campaignDescription',
        label: 'Campaign Description',
        type: 'textarea',
        placeholder: 'Describe what you want this campaign to achieve...',
        required: true,
        helpText: 'Be as detailed as possible - this helps us create the perfect script',
      },
      {
        name: 'targetCallVolume',
        label: 'How many calls do you plan to make?',
        type: 'select',
        options: [
          'Under 100',
          '100-500',
          '500-1,000',
          '1,000-5,000',
          '5,000-10,000',
          'Over 10,000',
        ],
        required: true,
      },
      {
        name: 'launchDate',
        label: 'Desired launch date',
        type: 'date',
        required: false,
      },
    ],
    required: true,
    estimatedMinutes: 8,
  },
  {
    type: 'form',
    title: 'Target Audience',
    description: 'Define who your AI will be calling',
    fields: [
      {
        name: 'targetAudience',
        label: 'Who are you calling?',
        type: 'textarea',
        placeholder: 'e.g., Small business owners in healthcare, B2B decision makers...',
        required: true,
      },
      {
        name: 'audienceIndustry',
        label: 'Target Industry/Sector',
        type: 'text',
        placeholder: 'e.g., Healthcare, Real Estate, Technology',
        required: false,
      },
      {
        name: 'audienceGeography',
        label: 'Geographic focus',
        type: 'text',
        placeholder: 'e.g., United States, California only, Canada',
        required: true,
      },
      {
        name: 'callTimePreference',
        label: 'Preferred calling hours',
        type: 'select',
        options: [
          'Business hours (9 AM - 5 PM)',
          'Extended hours (8 AM - 8 PM)',
          'Evenings only',
          'Weekends only',
          'Flexible - any time',
        ],
        required: true,
      },
      {
        name: 'audienceLanguage',
        label: 'Primary language',
        type: 'select',
        options: [
          'English',
          'Spanish',
          'French',
          'German',
          'Mandarin',
          'Other',
        ],
        required: true,
      },
    ],
    required: true,
    estimatedMinutes: 7,
  },
  {
    type: 'form',
    title: 'Call Script & Messaging',
    description: 'Help us craft the perfect conversation',
    fields: [
      {
        name: 'voicePersonality',
        label: 'Voice personality preference',
        type: 'select',
        options: [
          'Professional & Formal',
          'Friendly & Conversational',
          'Energetic & Enthusiastic',
          'Calm & Reassuring',
          'Direct & Concise',
        ],
        required: true,
      },
      {
        name: 'voiceGender',
        label: 'Voice gender preference',
        type: 'radio',
        options: ['Male', 'Female', 'No preference'],
        required: true,
      },
      {
        name: 'keyMessage',
        label: 'Key message or value proposition',
        type: 'textarea',
        placeholder: 'What is the main message you want to convey during the call?',
        required: true,
        helpText: 'This should be a clear, compelling reason for the recipient to engage',
      },
      {
        name: 'callToAction',
        label: 'Desired call-to-action',
        type: 'textarea',
        placeholder: 'e.g., Schedule a demo, Confirm attendance, Answer survey questions',
        required: true,
      },
      {
        name: 'scriptDraft',
        label: 'Do you have a script draft or talking points?',
        type: 'textarea',
        placeholder: 'Paste your draft script or key talking points here...',
        required: false,
        helpText: 'Optional - we can create one from scratch if you prefer',
      },
      {
        name: 'objectionHandling',
        label: 'Common objections and how to handle them',
        type: 'textarea',
        placeholder: 'e.g., "Not interested" → Acknowledge and offer value briefly...',
        required: false,
      },
    ],
    required: true,
    estimatedMinutes: 10,
  },
  {
    type: 'upload',
    title: 'Campaign Assets & Data',
    description: 'Upload any relevant files for your campaign',
    uploadCategories: [
      {
        name: 'call_list',
        label: 'Call List/Data',
        description: 'CSV or Excel file with phone numbers and contact info',
        accept: '.csv,.xlsx,.xls',
        maxFiles: 5,
        required: true,
      },
      {
        name: 'script_documents',
        label: 'Script Drafts',
        description: 'Any existing scripts, talking points, or messaging docs',
        accept: '.pdf,.doc,.docx,.txt',
        maxFiles: 3,
        required: false,
      },
      {
        name: 'reference_audio',
        label: 'Reference Audio (optional)',
        description: 'Example calls or voice samples for tone reference',
        accept: '.mp3,.wav,.m4a',
        maxFiles: 5,
        required: false,
      },
      {
        name: 'campaign_brief',
        label: 'Campaign Brief/Documents',
        description: 'Any additional campaign materials or brand guidelines',
        accept: '.pdf,.doc,.docx,.ppt,.pptx',
        maxFiles: 5,
        required: false,
      },
    ],
    required: false,
    estimatedMinutes: 6,
  },
  {
    type: 'form',
    title: 'Performance & Tracking',
    description: 'Define success metrics and tracking requirements',
    fields: [
      {
        name: 'kpis',
        label: 'Key Performance Indicators (KPIs)',
        type: 'checkbox',
        options: [
          'Call connection rate',
          'Conversation length',
          'Positive responses',
          'Appointments booked',
          'Conversions',
          'Call-to-action completion',
          'Customer satisfaction',
        ],
        required: true,
      },
      {
        name: 'successTarget',
        label: 'What would make this campaign successful?',
        type: 'textarea',
        placeholder: 'e.g., 500 qualified leads, 100 booked appointments, 20% positive response rate',
        required: true,
      },
      {
        name: 'integrations',
        label: 'Do you need any integrations?',
        type: 'checkbox',
        options: [
          'CRM integration (Salesforce, HubSpot, etc.)',
          'Calendar booking (Calendly, etc.)',
          'Email notifications',
          'Webhook/API integration',
          'Reporting dashboard',
          'SMS follow-up',
        ],
        required: false,
      },
      {
        name: 'reportingFrequency',
        label: 'How often would you like campaign reports?',
        type: 'select',
        options: ['Daily', 'Weekly', 'Bi-weekly', 'Monthly', 'Real-time dashboard only'],
        required: false,
      },
    ],
    required: true,
    estimatedMinutes: 6,
  },
  {
    type: 'form',
    title: 'Compliance & Legal',
    description: 'Important compliance information',
    fields: [
      {
        name: 'tcpaCompliance',
        label: 'TCPA Compliance Confirmation',
        type: 'checkbox',
        options: [
          'I confirm I have consent to call all contacts on my list',
          'I understand TCPA regulations apply to this campaign',
        ],
        required: true,
        helpText: 'Required for all calling campaigns',
      },
      {
        name: 'dncScrubbing',
        label: 'Do-Not-Call (DNC) scrubbing',
        type: 'radio',
        options: [
          'Yes, scrub against national DNC list',
          'No scrubbing needed (contacts already verified)',
        ],
        required: true,
      },
      {
        name: 'recordingConsent',
        label: 'Call recording',
        type: 'radio',
        options: [
          'Record all calls for quality assurance',
          'Do not record calls',
          'Record only with consent',
        ],
        required: true,
      },
      {
        name: 'additionalCompliance',
        label: 'Any other compliance requirements?',
        type: 'textarea',
        placeholder: 'e.g., Industry-specific regulations, state laws, company policies',
        required: false,
      },
    ],
    required: true,
    estimatedMinutes: 5,
  },
  {
    type: 'review',
    title: 'Review Your Campaign Details',
    description: `Please review all campaign information before submitting. Make sure your call list, script details, and compliance information are accurate.`,
    required: true,
    estimatedMinutes: 4,
  },
  {
    type: 'complete',
    title: 'Campaign Setup Complete!',
    description: `Excellent! Your voice AI campaign is ready for our team to build. We'll review your requirements, prepare the script, and set up your campaign. You'll receive a confirmation email with next steps, including script approval and test call scheduling. We're excited to launch this campaign with you!`,
    required: true,
    estimatedMinutes: 1,
  },
];
