/**
 * Web Design Onboarding Template
 * Comprehensive onboarding flow for web design projects
 */

import { OnboardingStep } from '../ai-onboarding-analyzer';

export const webDesignTemplate: OnboardingStep[] = [
  {
    type: 'welcome',
    title: 'Welcome to Your Web Design Project',
    description: `Thank you for choosing us for your web design project! This onboarding will take approximately 25-30 minutes to complete. We'll gather all the essential information and assets needed to bring your vision to life. Feel free to save your progress and return at any time.`,
    required: true,
    estimatedMinutes: 2,
  },
  {
    type: 'form',
    title: 'Brand & Business Information',
    description: 'Help us understand your brand and business goals',
    fields: [
      {
        name: 'businessName',
        label: 'Business/Brand Name',
        type: 'text',
        placeholder: 'e.g., Acme Corporation',
        required: true,
      },
      {
        name: 'tagline',
        label: 'Tagline or Slogan (if applicable)',
        type: 'text',
        placeholder: 'e.g., Innovation at its finest',
        required: false,
      },
      {
        name: 'businessDescription',
        label: 'What does your business do?',
        type: 'textarea',
        placeholder: 'Briefly describe your products, services, or mission...',
        required: true,
        helpText: 'This helps us understand your industry and target market',
      },
      {
        name: 'targetAudience',
        label: 'Who is your target audience?',
        type: 'textarea',
        placeholder: 'e.g., Small business owners, millennials, tech enthusiasts...',
        required: true,
      },
      {
        name: 'brandPersonality',
        label: 'How would you describe your brand personality?',
        type: 'select',
        options: [
          'Professional & Corporate',
          'Modern & Innovative',
          'Friendly & Approachable',
          'Bold & Energetic',
          'Elegant & Luxurious',
          'Playful & Creative',
          'Minimal & Clean',
          'Other',
        ],
        required: true,
      },
    ],
    required: true,
    estimatedMinutes: 8,
  },
  {
    type: 'upload',
    title: 'Brand Assets',
    description: 'Upload your brand materials to ensure design consistency',
    uploadCategories: [
      {
        name: 'logo',
        label: 'Logo Files',
        description: 'All versions of your logo (PNG, SVG, AI, etc.)',
        accept: 'image/*,.svg,.ai,.eps',
        maxFiles: 5,
        required: true,
      },
      {
        name: 'brand_guidelines',
        label: 'Brand Guidelines',
        description: 'Brand style guide, color palettes, typography rules',
        accept: '.pdf,.doc,.docx,.ppt,.pptx',
        maxFiles: 3,
        required: false,
      },
      {
        name: 'existing_assets',
        label: 'Existing Design Assets',
        description: 'Photos, icons, graphics you want us to use',
        accept: 'image/*',
        maxFiles: 10,
        required: false,
      },
    ],
    required: false,
    estimatedMinutes: 5,
  },
  {
    type: 'form',
    title: 'Website Goals & Features',
    description: 'Define what you want your website to achieve',
    fields: [
      {
        name: 'websiteGoal',
        label: 'Primary goal of the website',
        type: 'select',
        options: [
          'Generate leads',
          'Sell products (e-commerce)',
          'Provide information',
          'Build brand awareness',
          'Showcase portfolio',
          'Other',
        ],
        required: true,
      },
      {
        name: 'requiredPages',
        label: 'Which pages do you need?',
        type: 'checkbox',
        options: [
          'Home',
          'About Us',
          'Services/Products',
          'Portfolio/Gallery',
          'Blog',
          'Contact',
          'FAQ',
          'Testimonials',
          'Team',
        ],
        required: true,
      },
      {
        name: 'specialFeatures',
        label: 'Do you need any special features?',
        type: 'checkbox',
        options: [
          'Contact form',
          'Newsletter signup',
          'E-commerce/Shopping cart',
          'Blog/CMS',
          'Booking system',
          'Member login area',
          'Live chat',
          'Social media integration',
          'Search functionality',
          'Multi-language support',
        ],
        required: false,
      },
      {
        name: 'additionalRequirements',
        label: 'Any other specific requirements or features?',
        type: 'textarea',
        placeholder: 'Describe any custom functionality, integrations, or special requests...',
        required: false,
      },
    ],
    required: true,
    estimatedMinutes: 7,
  },
  {
    type: 'choice',
    title: 'Design Style Preferences',
    description: 'Select design styles that appeal to you (choose 2-3)',
    choices: [
      {
        id: 'modern_minimal',
        label: 'Modern & Minimal',
        description: 'Clean lines, lots of white space, simple typography',
      },
      {
        id: 'bold_colorful',
        label: 'Bold & Colorful',
        description: 'Vibrant colors, strong visuals, eye-catching elements',
      },
      {
        id: 'corporate_professional',
        label: 'Corporate & Professional',
        description: 'Traditional, trustworthy, business-focused design',
      },
      {
        id: 'creative_artistic',
        label: 'Creative & Artistic',
        description: 'Unique layouts, artistic elements, expressive design',
      },
      {
        id: 'tech_futuristic',
        label: 'Tech & Futuristic',
        description: 'Modern tech aesthetic, gradients, innovative design',
      },
      {
        id: 'elegant_luxury',
        label: 'Elegant & Luxury',
        description: 'Sophisticated, high-end, refined aesthetic',
      },
    ],
    required: true,
    estimatedMinutes: 4,
  },
  {
    type: 'upload',
    title: 'Content & Inspiration',
    description: 'Share content and examples to guide the design',
    uploadCategories: [
      {
        name: 'content_documents',
        label: 'Website Content',
        description: 'Text content, copy, or content outline for pages',
        accept: '.pdf,.doc,.docx,.txt',
        maxFiles: 5,
        required: false,
      },
      {
        name: 'competitor_examples',
        label: 'Competitor/Inspiration Examples',
        description: 'Screenshots or links to websites you like',
        accept: 'image/*,.pdf',
        maxFiles: 10,
        required: false,
        helpText: 'You can also paste website URLs in the next question',
      },
      {
        name: 'product_images',
        label: 'Product/Service Images',
        description: 'High-quality photos to feature on your site',
        accept: 'image/*',
        maxFiles: 20,
        required: false,
      },
    ],
    required: false,
    estimatedMinutes: 6,
  },
  {
    type: 'form',
    title: 'Technical & Timeline Details',
    description: 'Final details to get your project started',
    fields: [
      {
        name: 'exampleWebsites',
        label: 'Example websites you like (URLs)',
        type: 'textarea',
        placeholder: 'Paste website URLs, one per line...',
        required: false,
        helpText: 'What do you like about each site?',
      },
      {
        name: 'domainName',
        label: 'Do you have a domain name?',
        type: 'text',
        placeholder: 'e.g., www.example.com',
        required: false,
      },
      {
        name: 'hosting',
        label: 'Hosting preference',
        type: 'select',
        options: [
          'I need hosting included',
          'I have my own hosting',
          'I need guidance on hosting',
        ],
        required: false,
      },
      {
        name: 'launchDate',
        label: 'Desired launch date (if applicable)',
        type: 'date',
        required: false,
      },
      {
        name: 'additionalNotes',
        label: 'Anything else we should know?',
        type: 'textarea',
        placeholder: 'Any other details, concerns, or questions...',
        required: false,
      },
    ],
    required: false,
    estimatedMinutes: 5,
  },
  {
    type: 'review',
    title: 'Review Your Information',
    description: `Please review all the information you've provided. You can go back to any section to make changes before submitting.`,
    required: true,
    estimatedMinutes: 3,
  },
  {
    type: 'complete',
    title: 'Submission Complete!',
    description: `Thank you for completing the onboarding! We've received all your information and will begin working on your web design project. You'll receive a confirmation email shortly with next steps and a project timeline. If you have any questions, feel free to reach out to us at any time.`,
    required: true,
    estimatedMinutes: 1,
  },
];
